-- =============================================================================
-- V2__create_audit_log_table.sql
-- Creates the audit_log table (H2 compatible)
--
-- COBOL equivalent:
--   FD  AUDITLOG
--       LABEL RECORDS ARE STANDARD.
--   01  AUDIT-RECORD.
--     05 AUDIT-ENTITY-TYPE   PIC X(50).
--     05 AUDIT-ENTITY-ID     PIC X(50).
--     05 AUDIT-ACTION        PIC X(20).
--     05 AUDIT-CHANGED-BY    PIC X(50).
--     05 AUDIT-CHANGED-TS    PIC X(26).
--     05 AUDIT-OLD-VALUE     PIC X(4000).
--     05 AUDIT-NEW-VALUE     PIC X(4000).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Drop table if exists (H2 safe syntax)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS audit_log;

-- -----------------------------------------------------------------------------
-- audit_log table
-- H2 does not support JSONB - use CLOB for JSON storage
-- -----------------------------------------------------------------------------
CREATE TABLE audit_log (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type     VARCHAR(50)     NOT NULL,
    entity_id       VARCHAR(50)     NOT NULL,
    action          VARCHAR(20)     NOT NULL,
    changed_by      VARCHAR(50),
    changed_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    old_value       CLOB,
    new_value       CLOB,
    ip_address      VARCHAR(45),
    session_id      VARCHAR(100),

    -- Constraints
    CONSTRAINT chk_audit_log_action
        CHECK (action IN ('CREATE','UPDATE','DELETE','VIEW'))
);

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------
CREATE INDEX idx_audit_log_entity
    ON audit_log (entity_type, entity_id);

CREATE INDEX idx_audit_log_changed_at
    ON audit_log (changed_at);

CREATE INDEX idx_audit_log_changed_by
    ON audit_log (changed_by);

CREATE INDEX idx_audit_log_action
    ON audit_log (action);

CREATE INDEX idx_audit_log_entity_id
    ON audit_log (entity_id);