-- =============================================================================
-- V3__create_users_table.sql
-- Creates users and user_roles tables (H2 compatible)
--
-- COBOL equivalent:
--   EXEC CICS CREATE USERID(...)
--     DESCRIPTION(...)
--     PASSWORD(...)
--   END-EXEC
--
-- Replaces CICS RACF / external security manager user registry.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Drop tables if they exist (H2 safe syntax, order matters for FK)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;

-- -----------------------------------------------------------------------------
-- users table
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50)     NOT NULL,
    password        VARCHAR(255)    NOT NULL,
    email           VARCHAR(100)    NOT NULL,
    full_name       VARCHAR(100),
    enabled         BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT uq_users_username
        UNIQUE (username),

    CONSTRAINT uq_users_email
        UNIQUE (email),

    CONSTRAINT chk_users_username_not_empty
        CHECK (LENGTH(TRIM(username)) > 0),

    CONSTRAINT chk_users_password_not_empty
        CHECK (LENGTH(TRIM(password)) > 0)
);

-- -----------------------------------------------------------------------------
-- user_roles table
-- -----------------------------------------------------------------------------
CREATE TABLE user_roles (
    user_id         BIGINT          NOT NULL,
    role            VARCHAR(50)     NOT NULL,

    -- Composite PK
    CONSTRAINT pk_user_roles
        PRIMARY KEY (user_id, role),

    -- FK to users
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- Valid roles only
    CONSTRAINT chk_user_roles_role
        CHECK (role IN (
            'ROLE_ADMIN',
            'ROLE_USER',
            'ROLE_OPS',
            'ROLE_VIEWER'
        ))
);

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------
CREATE INDEX idx_users_username     ON users      (username);
CREATE INDEX idx_users_email        ON users      (email);
CREATE INDEX idx_users_enabled      ON users      (enabled);
CREATE INDEX idx_user_roles_user_id ON user_roles (user_id);
CREATE INDEX idx_user_roles_role    ON user_roles (role);

-- =============================================================================
-- Seed data - default application users
--
-- Passwords BCrypt encoded at strength 12:
--   admin   / Admin@123!
--   user    / User@123!
--   ops     / Ops@123!
--   viewer  / Viewer@123!
-- =============================================================================

INSERT INTO users (username, password, email, full_name, enabled, created_at)
VALUES
-- admin / Admin@123!
(
    'admin',
    '$2a$12$D5CTepAmJTV8uW93ZNGKoeCSa.B/Ukej.vLBO8Z0OOkgm7.sGiBCO',
    'admin@agilesolutions.com',
    'System Administrator',
    TRUE,
    CURRENT_TIMESTAMP
),
-- user / User@123!
(
    'user',
    '$2a$12$o3J5IgE8zbHe56tQUEbAPeH.HezR12LeZtXAtk2cs9mNEqRdvpotm',
    'user@agilesolutions.com',
    'Standard User',
    TRUE,
    CURRENT_TIMESTAMP
),
-- ops / Ops@123!
(
    'ops',
    '$2a$12$TrJnO3XIpAIdUeM4sAMvc.wt9gplXL4ZJb2IXtML1ZB3fwPSw9mei',
    'ops@agilesolutions.com',
    'Operations User',
    TRUE,
    CURRENT_TIMESTAMP
),
-- viewer / Viewer@123!
(
    'viewer',
    '$2a$12$hciyUdhTEFKPDaYMQY7pa.y29aOo1UQ3HMAslomjqtU5qRLMTC0da',
    'viewer@agilesolutions.com',
    'Read-Only Viewer',
    TRUE,
    CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- Role assignments
-- admin  -> ROLE_ADMIN + ROLE_USER
-- user   -> ROLE_USER
-- ops    -> ROLE_OPS  + ROLE_USER
-- viewer -> ROLE_VIEWER
-- -----------------------------------------------------------------------------
INSERT INTO user_roles (user_id, role)
SELECT id, 'ROLE_ADMIN' FROM users WHERE username = 'admin';

INSERT INTO user_roles (user_id, role)
SELECT id, 'ROLE_USER'  FROM users WHERE username = 'admin';

INSERT INTO user_roles (user_id, role)
SELECT id, 'ROLE_USER'  FROM users WHERE username = 'user';

INSERT INTO user_roles (user_id, role)
SELECT id, 'ROLE_OPS'   FROM users WHERE username = 'ops';

INSERT INTO user_roles (user_id, role)
SELECT id, 'ROLE_USER'  FROM users WHERE username = 'ops';

INSERT INTO user_roles (user_id, role)
SELECT id, 'ROLE_VIEWER' FROM users WHERE username = 'viewer';